### ISSUE TITLE
cross-en-de-roberta-sentence-transformer

### ISSUE THREAD

**Issue by ahmedm98** [PhilipMay/May.la#7]
Hello, 
for a university project, i am trying to compute similarity between texts. A I was trying to use "T-Systems-onsite/cross-en-de-roberta-sentence-transformer" I got confused about the output of the model.
when I do:
model = SentenceTransformer('T-Systems-onsite/cross-en-de-roberta-sentence-transformer')
out=model.encode(Hallo Welt!)
out has shape 768

but when i use : 
tokenizer = AutoTokenizer.from_pretrained(T-Systems-onsite/cross-en-de-roberta-sentence-transformer')
model = AutoModel.from_pretrained(T-Systems-onsite/cross-en-de-roberta-sentence-transformer')
tokenized_text = self.tokenizer("Hallo Welt", return_tensors="pt")
out=self.model(**tokenized_text)
out has a pooling_layer with shape 768 but is different from the output shape from above model  and a last_hidden_layer with shape [6,768]

so which are the embeddings to be used for semantic meaning?

sincerely,
a TUM student

**Comment by PhilipMay** [comment]
Hi!

I am glad that you are interested in my model.
The correct way to calculate the embeddings is described here: https://www.sbert.net/

The 2nd way you use the model exposes the raw output. 6 is the number of tokens the model sees. 
To calculate the embedding from this you have to average along the "time dimension" (the axes that is 6 long).

Hope that helps somehow. If yes - please close this issue. If not - feel free to ask. :-)

**Comment by ahmedm98** [comment]
yes thanks a lot
